# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [59]:
import numpy as np 
arr = np.arange(10)
arr_2D_2R = arr.reshape(2,5)
arr_2D_2R

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [60]:
arr1 = np.ones(10)
arr1 = arr1.reshape(2,5)
np.vstack((arr_2D_2R,arr1))

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [61]:
arr1 = np.ones(10)
arr1 = arr1.reshape(2,5)

np.hstack((arr_2D_2R,arr1))

array([[0., 1., 2., 3., 4., 1., 1., 1., 1., 1.],
       [5., 6., 7., 8., 9., 1., 1., 1., 1., 1.]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [62]:
arr_2D_2R.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [63]:
arr2 = np.arange(15)
arr2 = arr2.reshape(5,3)
arrw = arr2.flatten()
arrw

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [64]:
arrw.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [65]:
arr5 = np.arange(25)
arr5 = arr5.reshape(5,5)
np.square(arr5)

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [66]:
arr5_6 = np.arange(30)
arr5_6 = arr5_6.reshape(5,6)

np.mean(arr5_6)

14.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [67]:
arr5_6
np.std(arr5_6)

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [68]:
np.median(arr5_6)

14.5

## Question:11

### Find the transpose of the previous array in Q8?

In [69]:
np.transpose(arr5_6)

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [70]:
arr4_4 = np.arange(16)
arr4_4 = arr4_4.reshape(4,4)
# finding the diagnol element
a=np.diagonal(arr4_4)
# sum the elements
np.sum(a)

30

## Question:13

### Find the determinant of the previous array in Q12?

In [71]:
arr4_4 = np.arange(16)
arr4_4 = arr4_4.reshape(4,4)
np.linalg.det(arr4_4)

0.0

## Question:14

### Find the 5th and 95th percentile of an array?

In [72]:
print(np.percentile(arr4_4, 5))
print(np.percentile(arr4_4, 95))

0.75
14.25


## Question:15

### How to find if a given array has any null values?

In [73]:
ab = np.array([[1,2,3,4],[2,3,np.NaN,5],[np.NaN,5,2,3]])
np.argwhere(np.isnan(ab))

array([[1, 2],
       [2, 0]], dtype=int64)